name: Deploy Releases

on:
  release:
    types: [published]

env:
  HUSKY: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PROD_BUCKET: 'cloudflare-events'

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  deploy-core:
    uses: ./.github/workflows/deploy-npm.template.yml
    with:
      name: core
      working-directory: packages/core
    secrets: inherit

  deploy-browser:
    if: ${{ startsWith(github.event.release.tag_name, 'browser') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Parse version
        id: parse_version
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: echo "VERSION=${TAG##browser@}" >> $GITHUB_OUTPUT

      - name: Set version
        working-directory: packages/browser
        run: npm version ${{ steps.parse_version.outputs.VERSION }} --allow-same-version --no-commit-hooks --no-git-tag-version

      - name: Release to CDN
        working-directory: packages/browser
        env:
          PATH_VERSION: ${{ steps.parse_version.outputs.VERSION }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
        run: npm run release:cdn

      - name: Publish to NPM
        working-directory: packages/browser
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npm publish --access=public

  deploy-node:
    uses: ./.github/workflows/deploy-npm.template.yml
    with:
      name: node
      working-directory: packages/node
    secrets: inherit

  deploy-consent-tools:
    uses: ./.github/workflows/deploy-npm.template.yml
    with:
      name: consent-tools
      working-directory: packages/consent/consent-tools
    secrets: inherit

  deploy-consent-wrapper-onetrust:
    uses: ./.github/workflows/deploy-npm.template.yml
    with:
      name: consent-wrapper-onetrust
      working-directory: packages/consent/consent-wrapper-onetrust
    secrets: inherit
